name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:


jobs:

  build-and-test:

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        rust_channel:
          - stable
          - beta
          - nightly
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: x86_64-darwin
          - rust_channel: nightly
            experimental: true

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Adding `unstable` Nix channel
      run: |
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable
        nix-channel --update

    - name: Installing nixFlakes
      run: |
        nix-env -iA nixpkgs.nixFlakes
        echo 'experimental-features = nix-command flakes' | sudo tee -a /etc/nix/nix.conf
        echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH

    - uses: cachix/cachix-action@v8
      with:
        name: nickel
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Building Nickel against `${{ matrix.rust_channel }}` Rust channel
      run: |
        nix build ./#checks.${{ matrix.system }}.nickel-against-${{ matrix.rust_channel }}-rust-channel
